### ISSUE TITLE
Add start and end dates for the weeks

### ISSUE THREAD

**Issue by cdpaiva** [Code-the-Dream-School/dd-prac-team2-front#23]
In the mentor homepage, currently only the name of the week is displayed. It would be good if the start and end dates were also displayed, in a line right below the name of the week. The data is already available in the `Cohort` component.

I'm thinking about something similar to the following sketch, but it's just a suggestion, feel free to implement as you want.

![add-dates](https://github.com/Code-the-Dream-School/dd-prac-team2-front/assets/55894222/00ce79a3-6628-40db-8f7e-3381a3f34af5)

**Comment by Mbareck21** [comment]
I am working on this.

**Comment by Mbareck21** [comment]
Done
