### ISSUE TITLE
Improve the upcoming sessions interface

### ISSUE THREAD

**Issue by cdpaiva** [Code-the-Dream-School/dd-prac-team2-front#24]
When a mentor visits their Sessions page (component `<MentorSessions />`), the list of upcoming sessions is displayed.

This interface could be improved: style it with the same font as the rest of the app by using `<Typography />` elements, format the start date and time, and other changes you see fit.

This list will receive at most 6 sessions from the back-end. 

As a reference, this is what we have right now:

<img src="https://github.com/Code-the-Dream-School/dd-prac-team2-front/assets/55894222/aab6ab10-b661-49b7-b404-c44c1e9407c4" width="75%" height="75%">

**Comment by LiubovCass** [comment]
I would like to try. Luba (LiubovCass)

**Comment by Mbareck21** [comment]
I can help with this as well, if needed

**Comment by cdpaiva** [comment]
Closed by PR #66
