### ISSUE TITLE
Add pop-up notifications to user interactions

### ISSUE THREAD

**Issue by secch97** [Code-the-Dream-School/dd-prac-team2-front#26]
![image](https://github.com/Code-the-Dream-School/dd-prac-team2-front/assets/42615340/4e1e01e3-ac0a-4df6-b87a-27d4f877ebef)

Right now, our application does not show the user any notification message after interacting with a form (like successfully submitting data or getting an error). We would need to have pop-up notifications for such cases, either using:

- MUI Snackbars: [https://mui.com/material-ui/react-snackbar/](url)
- Other Toast notifications library like **React Toastify** [https://blog.logrocket.com/using-react-toastify-style-toast-messages/](url)

The task is to check every user interaction that uses a request. If the request is successful, then show a success message. If the request returns an error, show an error message. 

This change would be need to be applied on all the app (public, admin, mentor and student pages).

**Comment by LiubovCass** [comment]
Luba (LiubovCass)

**Comment by secch97** [comment]
> Luba (LiubovCass)

I will assign you this issue once you are invited to our repo!

**Comment by secch97** [comment]
Done on #72
