### ISSUE TITLE
Add a loading state when fetching requests.

### ISSUE THREAD

**Issue by secch97** [Code-the-Dream-School/dd-prac-team2-front#27]
![image](https://github.com/Code-the-Dream-School/dd-prac-team2-front/assets/42615340/035e5a4d-10a9-4766-8313-01f3c701d5ed)

Right now, our application does not render a **loading component** when the API requests are being sent and received on the following pages:
-- All admin pages.

The application does render a loading component on some student and mentor pages, but it would be best to have one constant loading component across all our application.

The task is to render a loading component when all the requests are still pending to be sent or received. 

You can help yourself by using:

- MUI Progress: [https://mui.com/material-ui/react-progress/](url)
- MUI Skeleton: [https://mui.com/material-ui/react-skeleton/](url)
- Other type of loading component of your choice.

**Comment by LiubovCass** [comment]
Luba(LiubovCass)

**Comment by secch97** [comment]
Done on [#72 ](https://github.com/Code-the-Dream-School/dd-prac-team2-front/pull/72)
