### ISSUE TITLE
Modify footer

### ISSUE THREAD

**Issue by secch97** [Code-the-Dream-School/dd-prac-team2-front#29]
<img width="1280" alt="image" src="https://github.com/Code-the-Dream-School/dd-prac-team2-front/assets/42615340/4bf7f95c-883a-4659-9a9e-3eae9450e529">

The task would be modifying app's footer to show the current members working on the app.

**Comment by LiubovCass** [comment]
Luba(LiubovCass)

**Comment by secch97** [comment]
Done on [PR #58](https://github.com/Code-the-Dream-School/dd-prac-team2-front/pull/58)
