### ISSUE TITLE
Render Comments in Student's Session Page

### ISSUE THREAD

**Issue by Miminiverse** [Code-the-Dream-School/dd-prac-team2-front#46]
Make a discussion board and renders all of the comments like a social media site. Each comment will have the name of the writer and date time created

**Comment by Mbareck21** [comment]
I think I did this

https://user-images.githubusercontent.com/93048977/265181211-bfcd2621-52f5-49e7-b201-784952a56f1a.png

**Comment by diorshelton** [comment]
Gotcha

**Comment by Miminiverse** [comment]
This is resolved
